### ISSUE TITLE
Date type conflicts with Foundation.Date

### ISSUE THREAD

**Issue by ruben-samsonyan** [vadymmarkov/Fakery#120] opened 2019-06-07 19:13 UTC
When I import Fakery and dry to define anything with `Date` type, Xcode gives an error `'Date' is ambiguous for type lookup in this context` because both Foundation and Fakery define it. Maybe to rename it, or to create a scope Fakery and put all fakery types in this scope? This will allow avoiding any conflicts

**Comment by ruben-samsonyan** [comment] 2019-06-07 19:45
I have changed all generator into an extension of Faker and have created a PR.

**Comment by EricWVGG** [comment] 2019-06-09 15:08
I crashed into this issue as well, thank you for fixing that…

**Comment by vadymmarkov** [comment] 2019-06-11 12:29
@ruben-samsonyan This can be fixed by specifying module namespace: `Fakery.Date`. Also, instead of using `Date` type directly it's better to do it through and instance of `Faker` class:

```swift
let faker = Faker(locale: "nb-NO")
faker.date.todayAddingYears(1)

```

**Comment by rubensamsonyanauto1** [comment] 2019-06-11 12:41
@vadymmarkov Thank you for your answer. That is the exact issue I'm facing with. Every time you define a variable with type `Date`, you should specify a namespace either `Foundation.Date` or `Fakery.Date`, which is very inconvenient.  For me, `Fakery` types should not conflict with anything in code, but instead, live in their own namespaces. Also, I can't use the method you proposed, because I need to define methods with `Date` arguments and variables with `Date` type. Maybe my solution is not the best, but I will appreciate it if this can be fixed in the next release.

**Comment by EricWVGG** [comment] 2019-06-11 13:27
"This can be fixed by specifying module namespace `Fakery.Date`. The problem is that we also have to namespace Foundation.Date and Foundation.Address. 

I think Foundation is a little too fundamental to be introducing competing types.

**Comment by vadymmarkov** [comment] 2019-06-11 16:57
You're right, now I see the problem. Your PR @rubensamsonyanauto1 has been approved and merged https://github.com/vadymmarkov/Fakery/pull/121. Closing this issue.

**Closed by vadymmarkov** 2019-06-11 16:57 UTC

**Comment by vadymmarkov** [comment] 2019-06-11 17:13
We could also use `Generator` suffix for all the names of generator classes. What do you think?

**Comment by rubensamsonyanauto1** [comment] 2019-06-14 07:39
For me one of the options is enough, I mean either generator suffix or namespace. Personally, I like a namespace. But as the types of Fakery are not being used directly, it really does not matter :) The only issue to not have commonly used names.

**Comment by EricWVGG** [comment] 2019-06-14 12:24
I think namespaces are a bit more elegant.
